version: 2

models:
  - name: categories
    description: Tabela utilizada para guardar as categorias dos pedidos.

    columns:
      - name: category_id
        description: Chave primária
      - name: category_name
        description: Nome da categoria
      - name: description
        description: Descrição da categoria
